Repository cse110-sp23-group1/Origami-Fortune-Teller, pull requests merged in 2023-06, with the labels that each got.

#19 origami image/operations
  .eslintrc.yml
  .gitignore
  assets/images/origami/1-Opened.svg
  assets/images/origami/2-Opened.svg
  assets/images/origami/3-Opened.svg
  assets/images/origami/4-Opened.svg
  assets/images/origami/5-Opened.svg
  assets/images/origami/6-Opened.svg
  assets/images/origami/7-Opened.svg
  assets/images/origami/8-opened.svg
  assets/images/origami/closed.svg
  assets/images/origami/horizontally-opened-nums.svg
  assets/images/origami/horizontally-opened.svg
  assets/images/origami/opened.svg
  assets/images/origami/vertically-opened-nums.svg
  assets/images/origami/vertically-opened.svg
  assets/media/CloseFortune.mov
  assets/media/OpenFortune.mov
  assets/scripts/Origami.js
  assets/scripts/SideBar.js
  assets/scripts/main.js
  assets/styles/main.css
  index.html
Labels: core

#46 Merge title header
  assets/styles/main.css
  index.html
Labels: core

#65 Fortunes are now on the Flaps of Origami
  assets/images/origami/1-Opened.svg
  assets/images/origami/2-Opened.svg
  assets/images/origami/3-Opened.svg
  assets/images/origami/4-Opened.svg
  assets/images/origami/5-Opened.svg
  assets/images/origami/6-Opened.svg
  assets/images/origami/7-Opened.svg
  assets/images/origami/8-opened.svg
  assets/scripts/Origami.js
  assets/styles/main.css
  index.html
Labels: enhancement

#69 Merge jsdocs implementation to main
  .github/workflows/jsdocs.yml
  CONTRIBUTING.md
  README.md
  assets/scripts/Origami.js
  conf.json
  package-lock.json
  package.json
Labels: documentation

#74 Merge testing
  assets/__tests__/origami.test.js
  assets/__tests__/userFlow.test.js
  assets/images/origami/horizontally-opened.svg
  assets/scripts/Origami.js
  assets/scripts/utilities/colors.js
  index.html
  jest-puppeteer.config.js
  package-lock.json
  package.json
Labels: testing
